### PR TITLE
Fix Kerberos username prompt errors

### LINKED ISSUE #10: Kerberos username prompt errors
I'm getting errors in the console that look like prompts for the Kerberos username:

    grails> run-app
    | Server running. Browse to http://localhost:8080/jsch-ssh2
    | Application loaded in interactive mode. Type 'stop-app' to shutdown.
    | Enter a script name to run. Use TAB for completion: 
    grails>
    | Error Kerberos username [bmaupin]: 
    grails>

I'm using `RunSshCommand` in my controller:

        render new RunSshCommand().execute() {
            host = "host.example.org"
            username = "user"
            command = "/usr/ucb/whoami"
            keyFile = "~/.ssh/id_rsa"
            knownHostsFile = null
            strictHostKeyChecking = "no"
        }

In Linux (Ubuntu 16.04) everything seems to work in spite of the errors, but in Windows (7) the application hangs and doesn't work.

### PR DESCRIPTION
**Pull request by bmaupin**
Seems like an issue with JSch (https://stackoverflow.com/a/10885420/399105). Fixes #10.

### CODE REVIEW

**Comment by michaelrice** [comment]
Can you rebase this so its only the 1 commit with the fix in it?

**Comment by bmaupin** [comment]
Done.

While we're on the topic is the build stuff from [the other commit](https://github.com/bmaupin/grails-jsch-ssh2/commit/6d4ffb5b952233b3e0120da478066d9ffad9818b) useful? I wasn't able to get Grails to run without those changes, but this is a bit new to me.

**Comment by michaelrice** [comment]
You can leave those changes in just rebase them into 1 commit is all I meant, sorry for the confusion.

**Comment by bmaupin** [comment]
Gotcha. How does that look?

**Comment by michaelrice** [comment]
👍

**Pull request merged**
